stages:
  - Package 🐳

package:
  stage: Package 🐳
  image: docker
  variables:
    IMAGE_TAGED: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build  -t $IMAGE_TAGED -f Dockerfile .
    - docker push $IMAGE_TAGED
